# Path to oh-my-zsh.
ZSH=$HOME/.oh-my-zsh

# Theme
ZSH_THEME="minimal"

# Plugins
plugins=(git systemd archlinux safe-paste z)

# Source Oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Root Path
ROOT_PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/kde/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/qt/bin"
HOME_PATH="$HOME/.cabal/bin:$HOME/bin"
export PATH="$HOME_PATH:$ROOT_PATH"

# Manpage colors
function man {
	LESS_TERMCAP_mb=$(tput bold; tput setaf 2) \
	LESS_TERMCAP_md=$(tput bold; tput setaf 74) \
	LESS_TERMCAP_me=$(tput sgr0) \
	LESS_TERMCAP_se=$(tput rmso; tput sgr0) \
	LESS_TERMCAP_us=$(tput smul; tput setaf 146) \
	LESS_TERMCAP_ue=$(tput rmul; tput sgr0) \
	/usr/bin/env man "$@"
}

# Aliases
alias ls='ls --color=auto'
alias tmux="tmux -2u"

# Keybinds
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
export KEYTIMEOUT=1
